# Generated by Django 6.0.1 on 2026-01-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shortener', '0002_alter_clickevent_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='referer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
