# Generated by Django 6.0.1 on 2026-01-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shortener', '0003_alter_clickevent_referer_alter_shortlink_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
