# Generated by Django 6.0.1 on 2026-01-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shortener', '0004_alter_shortlink_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='user_agent',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
