# Generated by Django 6.0.1 on 2026-01-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shortener', '0005_alter_clickevent_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='ip_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
